In [26]:
from brainbot.utils.tf import Transform, toTransform
from brainbot.kinematics.solvers import Ur5Kinematics
from brainbot.plan.regions import *
from brainbot.plan.samplers import *
from sklearn.mixture import GaussianMixture
from numpy.random import default_rng

In [2]:
# Hardcoded tf offsets for UR5
tool_tip_to_ee_tf = toTransform([-2.7292966e-04, -1.14038587e-04, 5.299999733e-01], [7.07322776e-01, 1.44034871e-04, -7.06890702e-01, -1.439925e-04])
world_to_base_tf = toTransform([0, 0, 2.3], [0,1,0,0])

In [3]:
# Make kinematic solver
solver = Ur5Kinematics(tool_tip_to_ee_tf.inv(), world_to_base_tf)

# Make cylinder
cyl = Cyl(0.25, 0.5, tf.toTransform([0,0,1.1], [0,0,0]))

In [4]:
# Can't use grapeshot in ipynb rn, just returning that every state is valid
def valid(state):
    return True

In [5]:
# Make sampler
s = RegionGridConfigSampler(cyl, [30, 30, 10], solver, valid)

In [6]:
# Test it works
s.next()

array([ 2.58377934, -1.19029593, -0.63113344, -0.21617846,  1.46288586,
        0.11998929])

In [ ]:
>>> X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
>>> gm = GaussianMixture(n_components=2, random_state=0).fit(X)
>>> gm.means_
array([[10.,  2.],
       [ 1.,  2.]])

In [9]:
num_data = 30 * 30 * 10
X = []
for _ in range(num_data):
    X.append(s.next())
    

In [12]:
gm = GaussianMixture(n_components=num_data, init_params='random_from_data', covariance_type='tied').fit(np.array(X))

In [18]:
config, label = gm.sample()

In [20]:
config[0]

array([-0.32591894, -0.83449059, -0.54299297, -1.07957339,  1.57654688,
        2.2284525 ])

In [50]:
rng = default_rng()
choice = rng.choice(np.array(X), (1,1), shuffle=False)[0][0]
print(f"Choose {choice}")

Choose [ 2.77895451 -2.13291717  2.15600443 -1.80163336  1.40320826  0.15401287]


In [53]:
rand_new = rng.normal(choice, scale = 0.1, size = (1, 6))

In [54]:
rand_new


array([[ 2.80792783, -2.15186747,  2.37821655, -1.76178645,  1.26384593,
         0.26914507]])