In [1]:
from brainbot.utils import tf
import numpy as np

pybullet build time: May 20 2022 19:45:31


In [2]:
a_b = np.array([0.5,0,0])
a_b_orien = np.array([0,0,1.57079633])

In [3]:
dir(tf)

['Transform',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__warningregistry__',
 'dataclass',
 'np',
 'pb',
 'rotationMatrixToQuaternion',
 'toRotationMatrix',
 'toTransform',
 'transformMatrixToTransform']

In [4]:
a_b_rot = tf.toRotationMatrix(a_b_orien)
a_b_rot

array([[-3.20510329e-09, -1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00, -3.20510329e-09,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [5]:
a_b_trans = tf.toTransform(a_b, a_b_orien)
a_b_trans

Transform(pos=array([0.5, 0. , 0. ]), quaternion=array([0.        , 0.        , 0.70710678, 0.70710678]), mat=matrix([[-3.20510329e-09, -1.00000000e+00,  0.00000000e+00,
          5.00000000e-01],
        [ 1.00000000e+00, -3.20510329e-09,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]))

In [11]:
a_b_trans.rigidTF().shape

(3, 4)

In [10]:
a_b_trans.mat[0:3,:].reshape(-1).tolist()[0]

[-3.2051032938795743e-09,
 -1.0,
 0.0,
 0.5,
 1.0,
 -3.2051032938795743e-09,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0]

In [6]:
b_c = np.array([0.5,0,0])
# b_c_euler = np.array([0,0,1.57079633])
b_c_euler = np.array([0,0,0,1])

In [7]:
tf.toRotationMatrix(b_c_euler)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
b_c_trans = tf.toTransform(b_c, b_c_euler)
b_c_trans

Transform(pos=array([0.5, 0. , 0. ]), quaternion=array([0, 0, 0, 1]), mat=matrix([[1. , 0. , 0. , 0.5],
        [0. , 1. , 0. , 0. ],
        [0. , 0. , 1. , 0. ],
        [0. , 0. , 0. , 1. ]]))

In [9]:
null_a = np.zeros((3))
null_a_q = np.array([0,0,0,1])
null_a_trans = tf.toTransform(null_a, null_a_q)
null_a_trans

Transform(pos=array([0., 0., 0.]), quaternion=array([0, 0, 0, 1]), mat=matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [10]:
# Should be same as a-b transform
# Starting at null, move to a 0.5 along x, rotate CCW 90 around z
null_b = null_a_trans * a_b_trans
null_b

Transform(pos=array([0.5, 0. , 0. ]), quaternion=array([0.        , 0.        , 0.70710677, 0.70710677]), mat=matrix([[ 0. , -1. ,  0. ,  0.5],
        [ 1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  1. ,  0. ],
        [ 0. ,  0. ,  0. ,  1. ]]))

In [11]:
# Starting at a, move 0.5 along x, do not rotate
null_c = null_b * b_c_trans
null_c

Transform(pos=array([0.5, 0.5, 0. ]), quaternion=array([0.        , 0.        , 0.70710677, 0.70710677]), mat=matrix([[ 0. , -1. ,  0. ,  0.5],
        [ 1. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  1. ,  0. ],
        [ 0. ,  0. ,  0. ,  1. ]]))

In [12]:
# Point should be (0.5,0.5,0)
print(null_c.pos)

[0.5 0.5 0. ]


In [15]:
null_c.mat[0:3,:]

matrix([[ 0. , -1. ,  0. ,  0.5],
        [ 1. ,  0. ,  0. ,  0.5],
        [ 0. ,  0. ,  1. ,  0. ]])